# Homework 1- Solution

Name: <b>Chetan</b>

Foundations Program, ktf-c1

# Answer - Question 1

## (1.1) Running tests for the Vector classes defined in Vector_Class.py

In [10]:
#Vector_Class.py contains class and methods for Vector Operations
import Vectors
from Vectors import Vector
import doctest
import numpy as np
doctest.testmod(Vectors,verbose=True)

Trying:
    v1 = Vector([4,2,7])
Expecting nothing
ok
Trying:
    v2 = Vector([1,-1,3])
Expecting nothing
ok
Trying:
    v1 + v2
Expecting:
    array([ 5,  1, 10])
ok
Trying:
    v1 + [-1,-1, 3]
Expecting:
    array([ 3,  1, 10])
ok
Trying:
    [-1, -1, 3] + v1
Expecting:
    array([ 3,  1, 10])
ok
Trying:
    v1 + range(3)
Expecting:
    array([4, 3, 9])
ok
Trying:
    v1 + range(2)
Expecting:
    array([4, 3, 7])
ok
Trying:
    range(2) + v1
Expecting:
    array([4, 3, 7])
ok
Trying:
    λ = 3
Expecting nothing
ok
Trying:
    v1*λ
Expecting:
    array([12,  6, 21])
ok
Trying:
    λ*v1
Expecting:
    array([12,  6, 21])
ok
Trying:
    v1@v2
Expecting:
    23
ok
Trying:
    v2@v1
Expecting:
    23
ok
Trying:
    v1 @ [-1, -1, 3]
Expecting:
    15
ok
Trying:
    [-1, -1, 3]@v1
Expecting:
    15
ok
Trying:
    v1.dot(v2)
Expecting:
    23
ok
Trying:
    v1.magnitude()
Expecting:
    8.306623862918075
ok
Trying:
    v2.magnitude()
Expecting:
    3.3166247903554
ok
Trying:
    v1.cos(v2)
E

TestResults(failed=0, attempted=23)

## (1.2) Defining helper functions for making the required Word Sets for the Plays

In [11]:
stopwords = ['also','sir','personã¦','my','“the','gave','hees','“my','often', 'twere','much','sometimes','hath','say','ligarius\x9d','aside', 'told','whiles','knew','bring','cause','whats','heres','dost','exit','said','lets','wherein','neither','canst','yea','indeed','shalt','yet','must','wherefore','enter','goes','oft','thus','didst','take','is','was','this','thats','act','let','enter''vpon','many','within','doth','put','wont','wouldst', 'wont','could', 'cannot', 'tis', 'thing','whereto','lookt','vsd','ith','giue','know','shall','come','comes','whose','would','alas','nay','though','hes','heerein','heeles','enough','another','may','thou','thee','lord','weeke', 'might', 'toward', 'sweaty', 'hast', 'Doth', 'make',"his","her",'tis','therefore','actus','not','cassius','how','thats','thy','till','himselfe','them','there','get','whos','well','like','i', 'me', 'my', 'myself', 'we', 'That','our', 'For','ours', 'whos','ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'it','whos','that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

def wordListToFreqDict(wordlist):
    """
       Converts List of words to Frequency Dictionary
       
       Input: List of words
       Output : Dictionary of word:frequency of word in list
    """
    wordfreq = [wordlist.count(p) for p in wordlist]
    return dict(list(zip(wordlist,wordfreq)))

def sortFreqDict(freqdict):
    """
       Sorts Dictionary to show values in Descending order
       Input: Frequency Dictionary
       Output : Sorted List of Tuples with Value and Key in Descending Order
    """
    aux = [(freqdict[key], key) for key in freqdict]
    aux.sort()
    aux.reverse()
    return aux

def removeStopWords(wordlist):
    """
       Removes Stopwords from list
       Input: List of words
       Output : list of words without the stopwords defined in 'stopwords' list
    """
    return [word for word in wordlist if word not in stopwords and len(word) > 2]

def flattenList(wordlist):
    """
       Converts a list of list into just one list
       Input: List of list of words
       Output : Flattened List with just one list containing all the words
       
    """
    return [item.lower() for sublist in wordlist if sublist for item in sublist]

def removeSpecialCharacter(wordlist,string = "&@#—%œ().,'’—[];™:-?12\x934567890!^`\~/_"):
    """
       Removes Special Characters from the words in the list
       Input: Wordlist - list of words, string - all the special characters to be removed
       Output : List of words without special characters
       
    """
    removetable = str.maketrans('', '', string)
    return [word.translate(removetable) for word in wordlist]
   

def makeWordList(filename):
    """
       Creates a list of all the words in the filename
       Input: filename of the file to be read
       Output : list of list of all the words in the file
       
    """
    fd = open(filename, encoding = "utf-8")
    wordlist = flattenList([line.strip().split()for line in fd.readlines()])
    fd.close()
    wordlist = removeSpecialCharacter(wordlist)
    wordlist = removeStopWords(wordlist)
    return wordlist
 

## (1.3) Creating a Union Set of all the words in the Plays

1. play_word_sets <- dict{play:set of all the words in that play} 
2. all_words <- set of union of words in all play

In [12]:
from os import listdir
import os
import pandas as pd

data_folder = './data'

all_words = set()
play_word_sets = dict()
for file in os.listdir(data_folder):
    if file.endswith(".txt"):
        play_word_sets[file] = set(makeWordList("data/"+file)) #creating a dictionary with {Play:Set of all words in Play}

#word union     
all_words = set.union(*[play_word_sets[key] for key in play_word_sets]) 

## (1.4) Creating a dictionary to hold the union words and its frequency of occurence in the Plays

1. w_list <- wordlist of all the words in the play
2. freqdict <- frequency dictionary of the words in the play 
3. common_vocab <- overall frequency dict of the union words and its frequency of occurence in the Plays

In [13]:
common_vocab = dict()
for file in os.listdir(data_folder):
    if file.endswith(".txt"):
        w_list = makeWordList("data/"+file)
        freqdict = wordListToFreqDict(w_list)
        common_vocab[file.replace('.txt','')] = [freqdict[word] if word in w_list else 0 for word in all_words]

## (1.5) Creating Dataframe of the Frequency Dictionary

In [14]:
vocab_df = pd.DataFrame(common_vocab)
vocab_df = vocab_df.transpose()
vocab_df.columns = [word for word in all_words]
vocab_df.head()

seruants  stopping  sending  truest  houres  calme  \
A Midsummer Night's Dream         0         0        0       3       0      0   
Hamlet                            2         1        2       0       2      1   
Julius Caesar                     0         0        0       0       0      0   
Romeo and Juliet                  0         0        1       0       0      0   
The Merchant of Venice            0         0        0       0       0      0   

                           eyed  scathe  prudence  filchd  ...  windlesses  \
A Midsummer Night's Dream     0       0         0       1  ...           0   
Hamlet                        0       0         0       0  ...           1   
Julius Caesar                 0       0         0       0  ...           0   
Romeo and Juliet              0       1         1       0  ...           0   
The Merchant of Venice        0       0         0       0  ...           0   

                           succession  blubbering  sings  oretooke  arrivd  \
A Midsummer Night's Dream           0           0      2         0       0   
Hamlet                              2           0      4         1       0   
Julius Caesar                       0           0      1         0       1   
Romeo and Juliet                    0           2      3         0       0   
The Merchant of Venice              0           0      2         0       0   

                           vnckle  puh  royally  curses  
A Midsummer Night's Dream       0    0        0       1  
Hamlet                          3    2        1       0  
Julius Caesar                   0    0        0       0  
Romeo and Juliet                0    0        0       0  
The Merchant of Venice          0    0        0       0  

[5 rows x 11798 columns]

## (1.6) Calculating the Cosine Similarity of the plays with each other

I used the method Vector.cos() from the Vector Class in order to calculate cosine similarity. 

In [15]:
import pprint
c_similarity = dict()
for key in common_vocab:
    A = Vector(common_vocab[key])
    c_similarity[key]= [A.cos(Vector(common_vocab[key])) for key in common_vocab]

## (1.7) Heatmap of the cosine similiarity of the Plays with each other

### Inferences:
1. A Midsummer Night's Dream is similar to Romeo & Juliet and The Merchant of Venice.
2. Hamlet is most similar to The Tempest.
3. Julius Caesar is most similar to The Merchant of Venice.
4. The Tempest is more similar to The Merchant of Venice than it is with Hamlet.


In [16]:
cosine_df = pd.DataFrame(c_similarity)
cosine_df = cosine_df.transpose()
cosine_df.columns = ["A Midsummer Night's Dream", 'Hamlet','Julius Caesar','Romeo and Juliet','The Merchant of Venice','The Tempest']
cosine_df.index = ["A Midsummer Night's Dream", 'Hamlet','Julius Caesar','Romeo and Juliet','The Merchant of Venice','The Tempest']
cosine_df.style.background_gradient(cmap='Blues')   

## (1.8) How to find the saddest play?

### High-level overview of the process:
    1. For word in play:
            if word's root or lemma is related to sadness:
                assign score : -1
            else:
                assign score : +1
    2. Compare the scores of all the plays, the one with the most negative score will be the saddest play. 

----------------------------------------------------------------------------------------------------------------

## Problem 2 - Solution

### numpy.ones()

try creating an array of given shape, 2 and type int , with ones.

In [17]:
a = np.ones(2, dtype = "int")
a

array([1, 1])

try creating an array of given shape, [3,3] and type int , with ones.

In [18]:
a = np.ones((3,3), dtype = "int")
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### numpy.zeros()

try creating an array of given shape, 4 and type int , with zeros.

In [19]:
a = np.zeros(4, dtype = "int")
a

array([0, 0, 0, 0])

try creating an array of given shape, [2,2] and type int , with zeros.

In [20]:
a = np.zeros((2,2), dtype = "int")
a

array([[0, 0],
       [0, 0]])

Similarly, try updating the data type to float

In [21]:
a = a.astype("float")
a

array([[0., 0.],
       [0., 0.]])

### np.dtype()

Create a datatype object of int16

In [22]:
st = np.dtype(np.int16)
st

dtype('int16')

### numpy.concatenate()

In [23]:
import numpy as np
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 


concatenate the given two arrays into a single array along the axis 0

In [24]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

concatenate the given two arrays into a single array along the axis 1

In [25]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### numpy.flatten()

In [26]:
a = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) 

In [27]:
a.flatten()

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

### numpy.ravel()

similarly flatten the given previous array to 1d array using numpy.ravel()

In [28]:
a.ravel()

array([1, 2, 3, 2, 4, 5, 1, 2, 3])